# Generated by Django 5.1.7 on 2025-03-30 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('confirmed', models.BooleanField(default=False)),
                ('service', models.CharField(choices=[('latte_art', 'Latte Art'), ('espresso_mastery', 'Espresso Mastery'), ('home_brewing', 'Home Brewing')], max_length=255)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='availabilities.availability')),
            ],
        ),
    ]
